name: Build Docs
on:
  push:
    branches:
      - develop

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Javadocs
        run: ./gradlew buildAggregatedJavadocs --continue

      - name: Build Antora-docs for openems.io
        run: ./gradlew buildAntoraDocs --continue

      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DOCS }}
          external_repository: OpenEMS/openems.io
          publish_branch: master
          publish_dir: build/www
